apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: excelify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: my-dockerhub-username/my-nextjs-app:latest   # 👈 replace with your image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
